# Testing Kinship functions

In [1]:
using Pkg, Revise

In [2]:
pwd()

"/Users/durbadalghosh/git/BigRiverQTL.jl/example"

In [3]:
Pkg.activate("..")

  Activating project at `~/git/BigRiverQTL.jl`


In [4]:
Pkg.instantiate()

### Libraries

In [5]:
using BigRiverQTL

In [6]:
using Statistics
using Distributed
using LinearAlgebra
import StatsBase: sample
# include("Miscellanea.jl")

### Data

In [7]:
#genoprob
gpr=[4.44965e-9  1.21848e-6  1.21848e-6  0.999998    8.34238e-16  2.23014e-12  2.23014e-12  1.0          8.34192e-16  2.25839e-12  2.25839e-12  1.0
 1.21848e-6  4.44965e-9  0.999998    1.21848e-6  2.23014e-12  8.34238e-16  1.0          2.23014e-12  2.25839e-12  8.34192e-16  1.0          2.25839e-12
 4.44965e-9  1.21848e-6  1.21848e-6  0.999998    8.34238e-16  2.23014e-12  2.23014e-12  1.0          8.34192e-16  2.25839e-12  2.25839e-12  1.0
 1.21848e-6  0.999998    4.44965e-9  1.21848e-6  2.23014e-12  1.0          8.34238e-16  2.23014e-12  2.25839e-12  1.0          8.34192e-16  2.25839e-12
 0.999998    1.21848e-6  1.21848e-6  4.44965e-9  1.0          2.23014e-12  2.23014e-12  8.34238e-16  1.0          2.25839e-12  2.25839e-12  8.34192e-16
 0.999998    1.21848e-6  1.21848e-6  4.44965e-9  1.0          2.23014e-12  2.23014e-12  8.34238e-16  1.0          2.25839e-12  2.25839e-12  8.34192e-16
 0.999998    1.21848e-6  1.21848e-6  4.44965e-9  1.0          2.23014e-12  2.23014e-12  8.34238e-16  1.0          2.25839e-12  2.25839e-12  8.34192e-16
 2.52546e-5  0.999973    2.03526e-7  1.21937e-6  0.000287185  0.999713     1.16563e-7   6.15819e-9   0.000315571  0.999684     1.1656e-7    6.76649e-9
 1.21848e-6  4.44965e-9  0.999998    1.21848e-6  2.23014e-12  8.34238e-16  1.0          2.23014e-12  2.25839e-12  8.34192e-16  1.0          2.25839e-12
 1.21848e-6  0.999998    4.44965e-9  1.21848e-6  2.23014e-12  1.0          8.34238e-16  2.23014e-12  2.25839e-12  1.0          8.34192e-16  2.25839e-12
 4.44965e-9  1.21848e-6  1.21848e-6  0.999998    8.34238e-16  2.23014e-12  2.23014e-12  1.0          8.34192e-16  2.25839e-12  2.25839e-12  1.0
 0.999998    1.21848e-6  1.21848e-6  4.44965e-9  1.0          2.23014e-12  2.23014e-12  8.34238e-16  1.0          2.25839e-12  2.25839e-12  8.34192e-16
 4.44965e-9  1.21848e-6  1.21848e-6  0.999998    8.34238e-16  2.23014e-12  2.23014e-12  1.0          8.34192e-16  2.25839e-12  2.25839e-12  1.0
 1.21848e-6  4.44965e-9  0.999998    1.21848e-6  2.23014e-12  8.34238e-16  1.0          2.23014e-12  2.25839e-12  8.34192e-16  1.0          2.25839e-12
 4.44965e-9  1.21848e-6  1.21848e-6  0.999998    8.34238e-16  2.23014e-12  2.23014e-12  1.0          8.34192e-16  2.25839e-12  2.25839e-12  1.0
 1.21848e-6  0.999998    4.44965e-9  1.21848e-6  2.23014e-12  1.0          8.34238e-16  2.23014e-12  2.25839e-12  1.0          8.34192e-16  2.25839e-12
 1.21848e-6  0.999998    4.44965e-9  1.21848e-6  2.23014e-12  1.0          8.34238e-16  2.23014e-12  2.25839e-12  1.0          8.34192e-16  2.25839e-12
 0.999998    1.21848e-6  1.21848e-6  4.44965e-9  1.0          2.23014e-12  2.23014e-12  8.34238e-16  1.0          2.25839e-12  2.25839e-12  8.34192e-16
 4.44965e-9  1.21848e-6  1.21848e-6  0.999998    8.34238e-16  2.23014e-12  2.23014e-12  1.0          8.34192e-16  2.25839e-12  2.25839e-12  1.0
 4.44965e-9  1.21848e-6  1.21848e-6  0.999998    8.34238e-16  2.23014e-12  2.23014e-12  1.0          8.34192e-16  2.25839e-12  2.25839e-12  1.0
]

20×12 Matrix{Float64}:
 4.44965e-9  1.21848e-6  1.21848e-6  0.999998    …  2.25839e-12  1.0
 1.21848e-6  4.44965e-9  0.999998    1.21848e-6     1.0          2.25839e-12
 4.44965e-9  1.21848e-6  1.21848e-6  0.999998       2.25839e-12  1.0
 1.21848e-6  0.999998    4.44965e-9  1.21848e-6     8.34192e-16  2.25839e-12
 0.999998    1.21848e-6  1.21848e-6  4.44965e-9     2.25839e-12  8.34192e-16
 0.999998    1.21848e-6  1.21848e-6  4.44965e-9  …  2.25839e-12  8.34192e-16
 0.999998    1.21848e-6  1.21848e-6  4.44965e-9     2.25839e-12  8.34192e-16
 2.52546e-5  0.999973    2.03526e-7  1.21937e-6     1.1656e-7    6.76649e-9
 1.21848e-6  4.44965e-9  0.999998    1.21848e-6     1.0          2.25839e-12
 1.21848e-6  0.999998    4.44965e-9  1.21848e-6     8.34192e-16  2.25839e-12
 4.44965e-9  1.21848e-6  1.21848e-6  0.999998    …  2.25839e-12  1.0
 0.999998    1.21848e-6  1.21848e-6  4.44965e-9     2.25839e-12  8.34192e-16
 4.44965e-9  1.21848e-6  1.21848e-6  0.999998       2.25839e-12  1.0
 1.21848e

In [8]:
# Another constructed data set
gene_mat=[[1 2 3 4 5 6]/sum([1 2 3 4 5 6]); [1 0 0 0 0 0]/sum([1 0 0 0 0 0]); [1001 1002 1003 1004 1005 1006]/sum([1001 1002 1003 1004 1005 1006]); 
    [1 2 3 4 5 6.1]/sum([1 2 3 4 5 6.1])]

4×6 Matrix{Float64}:
 0.047619   0.0952381  0.142857  0.190476  0.238095  0.285714
 1.0        0.0        0.0       0.0       0.0       0.0
 0.166251   0.166418   0.166584  0.16675   0.166916  0.167082
 0.0473934  0.0947867  0.14218   0.189573  0.236967  0.2891

In [9]:
# Another constructed data set for functions like "kinship_ctr" and "kinship_std".
gene_mat2=rand([0.0, 1.0, 2.0], 5, 10)

5×10 Matrix{Float64}:
 1.0  2.0  0.0  2.0  0.0  2.0  1.0  1.0  2.0  0.0
 1.0  2.0  0.0  1.0  2.0  2.0  1.0  1.0  2.0  2.0
 2.0  0.0  2.0  2.0  2.0  2.0  0.0  0.0  0.0  1.0
 1.0  0.0  2.0  2.0  2.0  0.0  1.0  0.0  0.0  1.0
 2.0  2.0  1.0  0.0  1.0  0.0  1.0  2.0  2.0  0.0

## Check the data sets for different functions:

### We will check the following properties for each kinship matrix: 
* Dimensions: $n \times n$ where $n$ is the number of subjects.
* All elements in the diagonals are $1$.
* All elements in each kinship matrix lie between $-1$ and $1$.
* Symmetric
* Positive Definite

We create a function "kinship_test" to test all the mentioned properties. 

In [10]:
# Checks the above mentioned properties
function kinship_test(kinmat::Matrix{Float64})
    a=zeros(4)
    
    #checking dimensions
    if(size(kinmat,1)==size(kinmat,2))
        a[1]=1
        else(a[1]==0)
        println("The matrix is not a square matrix.")
    end
    
    # checking if all elements between -1 and 1
    if(maximum(kinmat)<=1.0 && minimum(kinmat)>=-1.0)
        a[2]=1
        else(a[2]==0)
        println("Not all elements of the matrix lie between -1 and 1.")
    end

    # checking if all elements in the diagonal are 1
    if(diag(kinmat)==ones(size(kinmat,1)))
        a[3]=1
        else(a[3]==0)
        println("Not all elements of the diagonal  are 1.")
    end

    # checking if 'kinmat' symmetric and positive definite
    if(isposdef(kinmat)==1)
        a[4]=1
        else(a[4]==0)
        println("The matrix is not positive definite.")
    end
    
    if(a==ones(4))
        println("All mentioned properties of a kinship matrix are satisfied.")
        
    
    
    
    
    
    
        
    
        

    end
        
        
end
    

kinship_test (generic function with 1 method)

## Testing "calckinship"

In [11]:
A=calckinship(gpr)

20×20 Matrix{Float64}:
 1.0       0.5       0.999999  0.5       …  0.5       0.999999  0.999999
 0.5       1.0       0.5       0.5          0.5       0.5       0.5
 0.999999  0.5       1.0       0.5          0.5       0.999999  0.999999
 0.5       0.5       0.5       1.0          0.5       0.5       0.5
 0.5       0.5       0.5       0.5          0.999999  0.5       0.5
 0.5       0.5       0.5       0.5       …  0.999999  0.5       0.5
 0.5       0.5       0.5       0.5          0.999999  0.5       0.5
 0.5       0.5       0.5       0.999895     0.500105  0.5       0.5
 0.5       0.999999  0.5       0.5          0.5       0.5       0.5
 0.5       0.5       0.5       0.999999     0.5       0.5       0.5
 0.999999  0.5       0.999999  0.5       …  0.5       0.999999  0.999999
 0.5       0.5       0.5       0.5          0.999999  0.5       0.5
 0.999999  0.5       0.999999  0.5          0.5       0.999999  0.999999
 0.5       0.999999  0.5       0.5          0.5       0.5       0.5
 0.99

In [12]:
kinship_test(A)

All mentioned properties of a kinship matrix are satisfied.


In [13]:
A=calckinship(gene_mat)

4×4 Matrix{Float64}:
 1.0       0.68254   0.722268  0.735575
 0.68254   1.0       0.722084  0.682464
 0.722268  0.722084  1.0       0.722269
 0.735575  0.682464  0.722269  1.0

In [14]:
kinship_test(A)

All mentioned properties of a kinship matrix are satisfied.


***Testing "kinship_man"***

In [15]:
A=kinship_man(gpr)

12×12 Matrix{Float64}:
 1.0       0.500003  0.599999  0.4       …  0.500018  0.599999  0.399999
 0.500003  1.0       0.600002  0.400003     0.999984  0.600001  0.400002
 0.599999  0.600002  1.0       0.500001     0.600015  0.999999  0.5
 0.4       0.400003  0.500001  1.0          0.400017  0.500001  0.999999
 0.999986  0.500016  0.599986  0.399986     0.50003   0.599986  0.399986
 0.500016  0.999986  0.600014  0.400015  …  0.999999  0.600014  0.400014
 0.599999  0.600001  0.999999  0.500001     0.600016  1.0       0.5
 0.399999  0.400002  0.5       0.999999     0.400016  0.5       1.0
 0.999985  0.500017  0.599984  0.399985     0.500032  0.599984  0.399984
 0.500018  0.999984  0.600015  0.400017     1.0       0.600016  0.400016
 0.599999  0.600001  0.999999  0.500001  …  0.600016  1.0       0.5
 0.399999  0.400002  0.5       0.999999     0.400016  0.5       1.0

In [16]:
kinship_test(A)

All mentioned properties of a kinship matrix are satisfied.


In [17]:
A=kinship_man(gene_mat)

6×6 Matrix{Float64}:
 1.0       0.726205  0.702411  0.678616  0.654822  0.629842
 0.726205  1.0       0.976205  0.952411  0.928616  0.903637
 0.702411  0.976205  1.0       0.976205  0.952411  0.927431
 0.678616  0.952411  0.976205  1.0       0.976205  0.951226
 0.654822  0.928616  0.952411  0.976205  1.0       0.975021
 0.629842  0.903637  0.927431  0.951226  0.975021  1.0

In [18]:
kinship_test(A)

All mentioned properties of a kinship matrix are satisfied.


***Testing "kinship_lin"***

In [19]:
A=kinship_lin(gpr,1)

12×12 Matrix{Float64}:
 1.0         1.81101e-6  4.87391e-7  2.67184e-9  …  1.82773e-7   1.55739e-9
 1.81101e-6  1.0         1.17343e-8  7.3113e-7      6.49529e-9   4.26807e-7
 4.87391e-7  1.17343e-8  1.0         6.09239e-7     0.15         4.26468e-7
 2.67184e-9  7.3113e-7   6.09239e-7  1.0            1.82773e-7   0.349999
 0.25        1.46635e-5  3.04623e-7  1.12992e-9     2.57283e-12  9.76623e-14
 1.50606e-6  0.249984    1.10633e-8  3.04648e-7  …  5.82633e-9   3.3946e-10
 1.82773e-7  6.49544e-9  0.15        1.82773e-7     0.15         1.11935e-12
 1.55739e-9  4.26776e-7  4.26468e-7  0.349999       1.12499e-12  0.35
 0.25        1.60827e-5  3.04624e-7  1.13165e-9     2.7425e-12   1.07266e-13
 1.50603e-6  0.249982    1.1063e-8   3.04646e-7     5.82616e-9   3.3946e-10
 1.82773e-7  6.49529e-9  0.15        1.82773e-7  …  1.0          1.12923e-12
 1.55739e-9  4.26807e-7  4.26468e-7  0.349999       1.12923e-12  1.0

In [20]:
kinship_test(A)

All mentioned properties of a kinship matrix are satisfied.


In [21]:
kinship_lin(gene_mat,1)

6×6 Matrix{Float64}:
 1.0         0.00917364  0.010309   0.0114443  0.0125796  0.0137711
 0.00917364  1.0         0.0137012  0.0159649  0.0182287  0.0206048
 0.010309    0.0137012   1.0        0.0204856  0.0238778  0.0274384
 0.0114443   0.0159649   0.0204856  1.0        0.0295268  0.0342721
 0.0125796   0.0182287   0.0238778  0.0295268  1.0        0.0411057
 0.0137711   0.0206048   0.0274384  0.0342721  0.0411057  1.0

In [22]:
kinship_test(A)

All mentioned properties of a kinship matrix are satisfied.


***Testing "kinship_ctr"***

In [38]:
A=kinship_ctr(gene_mat2)

10×10 Matrix{Float64}:
  0.36        -0.12          0.3   …  -0.02  -0.12         -0.24
 -0.12         0.8          -0.78      0.5    0.8          -0.32
  0.3         -0.78          1.04     -0.28  -0.78          0.1
 -6.4837e-17  -0.48          0.34     -0.58  -0.48          1.77636e-18
  0.14        -0.54          0.48     -0.44  -0.54          0.34
 -0.12         1.77636e-18  -0.38  …  -0.3    1.77636e-18   0.08
 -0.18         0.14         -0.04      0.24   0.14          0.02
 -0.02         0.5          -0.28      0.6    0.5          -0.22
 -0.12         0.8          -0.78      0.5    0.8          -0.32
 -0.24        -0.32          0.1      -0.22  -0.32          0.56

In [24]:
kinship_test(A)

Not all elements of the matrix lie between -1 and 1.
Not all elements of the diagonal  are 1.
The matrix is not positive definite.


***Testing "kinship_std"***

In [25]:
A=kinship_std(gene_mat2)

10×10 Matrix{Float64}:
  0.445797   -0.134059    0.426824   …   0.0556646  -0.134059   -0.343341
 -0.134059    1.0259     -1.08386        0.545668    1.0259     -0.37048
  0.426824   -1.08386     1.59955       -0.224177   -1.08386     0.0112049
 -0.0237687  -0.603624    0.478998      -0.67477    -0.603624   -0.0302971
  0.0995515  -0.592952    0.454097      -0.55145    -0.592952    0.502114
 -0.239579    0.111396   -0.667642   …  -0.368841    0.111396    0.162984
 -0.153031    0.0761025   0.0888662      0.265826    0.0761025  -0.0159346
  0.0556646   0.545668   -0.224177       0.735391    0.545668   -0.328978
 -0.134059    1.0259     -1.08386        0.545668    1.0259     -0.37048
 -0.343341   -0.37048     0.0112049     -0.328978   -0.37048     0.783208

In [26]:
kinship_test(A)

Not all elements of the matrix lie between -1 and 1.
Not all elements of the diagonal  are 1.
The matrix is not positive definite.


***Testing "kinship_gs"***

In [27]:
A=kinship_gs(gpr,.9)

12×12 Matrix{Float64}:
 1.0       0.573759  0.641182  0.513418  …  0.573776  0.641181  0.513418
 0.573759  1.0       0.641183  0.513421     1.0       0.641183  0.51342
 0.641182  0.641183  1.0       0.573755     0.641203  1.0       0.573754
 0.513418  0.513421  0.573755  1.0          0.513436  0.573755  1.0
 1.0       0.573774  0.641181  0.513418     0.573792  0.64118   0.513417
 0.573774  1.0       0.641201  0.513435  …  1.0       0.641201  0.513433
 0.641181  0.641183  1.0       0.573755     0.641203  1.0       0.573753
 0.513418  0.51342   0.573754  1.0          0.513435  0.573753  1.0
 1.0       0.573776  0.641181  0.513418     0.573794  0.64118   0.513417
 0.573776  1.0       0.641203  0.513436     1.0       0.641203  0.513435
 0.641181  0.641183  1.0       0.573755  …  0.641203  1.0       0.573753
 0.513418  0.51342   0.573754  1.0          0.513435  0.573753  1.0

In [28]:
kinship_test(A)

The matrix is not positive definite.


In [29]:
eigvals(A)

12-element Vector{Float64}:
 -3.3890219084130043e-16
  3.343379243579535e-18
  2.5619639417050724e-15
  8.707340037115258e-15
  4.618277161739736e-13
  1.658918297073593e-12
  2.6019677547443854e-9
  7.830101886748021e-9
  0.9919112834404391
  1.2786577053877741
  1.5336564726604949
  8.19577452807709

In [30]:
A=kinship_gs(gene_mat,.9)

6×6 Matrix{Float64}:
 1.0       0.756516  0.753676  0.748966  0.742421  0.733628
 0.756516  1.0       0.998747  0.994997  0.988779  0.979644
 0.753676  0.998747  1.0       0.998747  0.994997  0.988403
 0.748966  0.994997  0.998747  1.0       0.998747  0.994743
 0.742421  0.988779  0.994997  0.998747  1.0       0.998616
 0.733628  0.979644  0.988403  0.994743  0.998616  1.0

In [31]:
kinship_test(A)

All mentioned properties of a kinship matrix are satisfied.


***Testing "kinship_4way"***

In [32]:
A=kinship_4way(gpr)

12×12 Matrix{Float64}:
 1.0    0.5  0.5  0.675  0.5    0.5  0.5    0.5    0.5    0.5  0.5    0.5
 0.5    1.0  0.8  0.5    0.5    0.5  0.5    0.5    0.5    0.5  0.5    0.5
 0.5    0.8  1.0  0.5    0.5    0.5  0.5    0.5    0.5    0.5  0.5    0.5
 0.675  0.5  0.5  1.0    0.5    0.5  0.5    0.5    0.5    0.5  0.5    0.5
 0.5    0.5  0.5  0.5    1.0    0.5  0.5    0.675  0.625  0.5  0.5    0.5
 0.5    0.5  0.5  0.5    0.5    1.0  0.8    0.5    0.5    0.6  0.5    0.5
 0.5    0.5  0.5  0.5    0.5    0.8  1.0    0.5    0.5    0.5  0.575  0.5
 0.5    0.5  0.5  0.5    0.675  0.5  0.5    1.0    0.5    0.5  0.5    0.675
 0.5    0.5  0.5  0.5    0.625  0.5  0.5    0.5    1.0    0.5  0.5    0.675
 0.5    0.5  0.5  0.5    0.5    0.6  0.5    0.5    0.5    1.0  0.8    0.5
 0.5    0.5  0.5  0.5    0.5    0.5  0.575  0.5    0.5    0.8  1.0    0.5
 0.5    0.5  0.5  0.5    0.5    0.5  0.5    0.675  0.675  0.5  0.5    1.0

In [33]:
kinship_test(A)

All mentioned properties of a kinship matrix are satisfied.


In [34]:
A=kinship_4way(gene_mat)

6×6 Matrix{Float64}:
 1.0  0.5    0.5    0.5    0.5    0.5
 0.5  1.0    0.625  0.625  0.625  0.625
 0.5  0.625  1.0    0.625  0.625  0.625
 0.5  0.625  0.625  1.0    0.625  0.625
 0.5  0.625  0.625  0.625  1.0    0.625
 0.5  0.625  0.625  0.625  0.625  1.0

In [35]:
kinship_test(A)

All mentioned properties of a kinship matrix are satisfied.


In [36]:
BLAS.syrk

syrk (generic function with 2 methods)

In [39]:
eigvals(A)

10-element Vector{Float64}:
 -1.7216490268634744e-16
 -7.826551404546656e-17
  5.953972753597669e-17
  2.27916078407676e-16
  3.7174246919205995e-16
  0.2999751999533997
  0.5603858822989087
  0.8548038399733343
  1.4837582326376284
  3.6010768451367294