# Testing Kinship functions

In [45]:
using Pkg, Revise

In [46]:
pwd()

"/Users/durbadalghosh/git/BigRiverQTL.jl/example"

In [47]:
Pkg.activate("..")

  Activating project at `~/git/BigRiverQTL.jl`


In [48]:
Pkg.instantiate()

### Libraries

In [49]:
using BigRiverQTL

In [50]:

using Statistics
using Distributed
using LinearAlgebra
import StatsBase: sample

# include("Miscellanea.jl")


### Data

In [51]:
#genoprob
gpr=[4.44965e-9  1.21848e-6  1.21848e-6  0.999998    8.34238e-16  2.23014e-12  2.23014e-12  1.0          8.34192e-16  2.25839e-12  2.25839e-12  1.0
 1.21848e-6  4.44965e-9  0.999998    1.21848e-6  2.23014e-12  8.34238e-16  1.0          2.23014e-12  2.25839e-12  8.34192e-16  1.0          2.25839e-12
 4.44965e-9  1.21848e-6  1.21848e-6  0.999998    8.34238e-16  2.23014e-12  2.23014e-12  1.0          8.34192e-16  2.25839e-12  2.25839e-12  1.0
 1.21848e-6  0.999998    4.44965e-9  1.21848e-6  2.23014e-12  1.0          8.34238e-16  2.23014e-12  2.25839e-12  1.0          8.34192e-16  2.25839e-12
 0.999998    1.21848e-6  1.21848e-6  4.44965e-9  1.0          2.23014e-12  2.23014e-12  8.34238e-16  1.0          2.25839e-12  2.25839e-12  8.34192e-16
 0.999998    1.21848e-6  1.21848e-6  4.44965e-9  1.0          2.23014e-12  2.23014e-12  8.34238e-16  1.0          2.25839e-12  2.25839e-12  8.34192e-16
 0.999998    1.21848e-6  1.21848e-6  4.44965e-9  1.0          2.23014e-12  2.23014e-12  8.34238e-16  1.0          2.25839e-12  2.25839e-12  8.34192e-16
 2.52546e-5  0.999973    2.03526e-7  1.21937e-6  0.000287185  0.999713     1.16563e-7   6.15819e-9   0.000315571  0.999684     1.1656e-7    6.76649e-9
 1.21848e-6  4.44965e-9  0.999998    1.21848e-6  2.23014e-12  8.34238e-16  1.0          2.23014e-12  2.25839e-12  8.34192e-16  1.0          2.25839e-12
 1.21848e-6  0.999998    4.44965e-9  1.21848e-6  2.23014e-12  1.0          8.34238e-16  2.23014e-12  2.25839e-12  1.0          8.34192e-16  2.25839e-12
 4.44965e-9  1.21848e-6  1.21848e-6  0.999998    8.34238e-16  2.23014e-12  2.23014e-12  1.0          8.34192e-16  2.25839e-12  2.25839e-12  1.0
 0.999998    1.21848e-6  1.21848e-6  4.44965e-9  1.0          2.23014e-12  2.23014e-12  8.34238e-16  1.0          2.25839e-12  2.25839e-12  8.34192e-16
 4.44965e-9  1.21848e-6  1.21848e-6  0.999998    8.34238e-16  2.23014e-12  2.23014e-12  1.0          8.34192e-16  2.25839e-12  2.25839e-12  1.0
 1.21848e-6  4.44965e-9  0.999998    1.21848e-6  2.23014e-12  8.34238e-16  1.0          2.23014e-12  2.25839e-12  8.34192e-16  1.0          2.25839e-12
 4.44965e-9  1.21848e-6  1.21848e-6  0.999998    8.34238e-16  2.23014e-12  2.23014e-12  1.0          8.34192e-16  2.25839e-12  2.25839e-12  1.0
 1.21848e-6  0.999998    4.44965e-9  1.21848e-6  2.23014e-12  1.0          8.34238e-16  2.23014e-12  2.25839e-12  1.0          8.34192e-16  2.25839e-12
 1.21848e-6  0.999998    4.44965e-9  1.21848e-6  2.23014e-12  1.0          8.34238e-16  2.23014e-12  2.25839e-12  1.0          8.34192e-16  2.25839e-12
 0.999998    1.21848e-6  1.21848e-6  4.44965e-9  1.0          2.23014e-12  2.23014e-12  8.34238e-16  1.0          2.25839e-12  2.25839e-12  8.34192e-16
 4.44965e-9  1.21848e-6  1.21848e-6  0.999998    8.34238e-16  2.23014e-12  2.23014e-12  1.0          8.34192e-16  2.25839e-12  2.25839e-12  1.0
 4.44965e-9  1.21848e-6  1.21848e-6  0.999998    8.34238e-16  2.23014e-12  2.23014e-12  1.0          8.34192e-16  2.25839e-12  2.25839e-12  1.0
]


20×12 Matrix{Float64}:
 4.44965e-9  1.21848e-6  1.21848e-6  0.999998    …  2.25839e-12  1.0
 1.21848e-6  4.44965e-9  0.999998    1.21848e-6     1.0          2.25839e-12
 4.44965e-9  1.21848e-6  1.21848e-6  0.999998       2.25839e-12  1.0
 1.21848e-6  0.999998    4.44965e-9  1.21848e-6     8.34192e-16  2.25839e-12
 0.999998    1.21848e-6  1.21848e-6  4.44965e-9     2.25839e-12  8.34192e-16
 0.999998    1.21848e-6  1.21848e-6  4.44965e-9  …  2.25839e-12  8.34192e-16
 0.999998    1.21848e-6  1.21848e-6  4.44965e-9     2.25839e-12  8.34192e-16
 2.52546e-5  0.999973    2.03526e-7  1.21937e-6     1.1656e-7    6.76649e-9
 1.21848e-6  4.44965e-9  0.999998    1.21848e-6     1.0          2.25839e-12
 1.21848e-6  0.999998    4.44965e-9  1.21848e-6     8.34192e-16  2.25839e-12
 4.44965e-9  1.21848e-6  1.21848e-6  0.999998    …  2.25839e-12  1.0
 0.999998    1.21848e-6  1.21848e-6  4.44965e-9     2.25839e-12  8.34192e-16
 4.44965e-9  1.21848e-6  1.21848e-6  0.999998       2.25839e-12  1.0
 1.21848e

In [52]:
# Another constructed data set
gene_mat=[[1 2 3 4 5 6]/sum([1 2 3 4 5 6]); [1 0 0 0 0 0]/sum([1 0 0 0 0 0]); [1001 1002 1003 1004 1005 1006]/sum([1001 1002 1003 1004 1005 1006]); 
    [1 2 3 4 5 6.1]/sum([1 2 3 4 5 6.1])]


4×6 Matrix{Float64}:
 0.047619   0.0952381  0.142857  0.190476  0.238095  0.285714
 1.0        0.0        0.0       0.0       0.0       0.0
 0.166251   0.166418   0.166584  0.16675   0.166916  0.167082
 0.0473934  0.0947867  0.14218   0.189573  0.236967  0.2891

## Check the data sets for different functions:

In [53]:
# testing calckinship


function calckinship(geno::Matrix{Float64})

    # get dimensions
    sz = size(geno)

    # assign to variables for convenience
    nr = sz[1]
    nc = sz[2]

    # if empty then there is nothing to do
    if(nr==0)
        error("Nothing to do here.")
    else
        # make matrix to hold distances
        d = zeros(nr,nr)
    end

    # assign diagonals to ones
    for i=1:nr
        d[i,i] = 1.0
    end

    ncomplete = nc
    # off-diagonal elements need to be calculated
    if(nr>=2)
        for i=1:(nr-1)
            for j=(i+1):nr
                p1 = geno[i,:]
                p2 = geno[j,:]
                d[i,j] = d[j,i] = sum( p1 .* p2 + (1 .- p1) .* (1 .- p2) ) / ncomplete

            end
        end
    end
    return d
end

calckinship (generic function with 1 method)

In [54]:
calckinship(gpr)

20×20 Matrix{Float64}:
 1.0       0.5       0.999999  0.5       …  0.5       0.999999  0.999999
 0.5       1.0       0.5       0.5          0.5       0.5       0.5
 0.999999  0.5       1.0       0.5          0.5       0.999999  0.999999
 0.5       0.5       0.5       1.0          0.5       0.5       0.5
 0.5       0.5       0.5       0.5          0.999999  0.5       0.5
 0.5       0.5       0.5       0.5       …  0.999999  0.5       0.5
 0.5       0.5       0.5       0.5          0.999999  0.5       0.5
 0.5       0.5       0.5       0.999895     0.500105  0.5       0.5
 0.5       0.999999  0.5       0.5          0.5       0.5       0.5
 0.5       0.5       0.5       0.999999     0.5       0.5       0.5
 0.999999  0.5       0.999999  0.5       …  0.5       0.999999  0.999999
 0.5       0.5       0.5       0.5          0.999999  0.5       0.5
 0.999999  0.5       0.999999  0.5          0.5       0.999999  0.999999
 0.5       0.999999  0.5       0.5          0.5       0.5       0.5
 0.99

In [55]:
calckinship(gene_mat)

4×4 Matrix{Float64}:
 1.0       0.68254   0.722268  0.735575
 0.68254   1.0       0.722084  0.682464
 0.722268  0.722084  1.0       0.722269
 0.735575  0.682464  0.722269  1.0

In [56]:
# testing kinship_man
function kinship_man(genematrix::Matrix{Float64})
#    c0=findall(.!isna.(genematrix[1,:]));
#    c1=findall(.!isna.(genematrix[2,:]));
#    ckeep=intersect(c0,c1);
#                  for j=3:nrow
#                  ck=find(.!isna.(genematrix[j,:]));
#                  ckeep=intersect(ck,ckeep);
#                   end
#                         geneupdate = genematrix[:,ckeep];
                        col = axes(genematrix,2)
                    kin=zeros(col,col);
                        @views for c=col, r=c:length(col)
                            kin[r,c]= 1.0-mean(abs.(genematrix[:,c]-genematrix[:,r]))
                                    kin[c,r]=kin[r,c]
                        end

return kin

end


kinship_man (generic function with 1 method)

In [57]:
kinship_man(gpr)

12×12 Matrix{Float64}:
 1.0       0.500003  0.599999  0.4       …  0.500018  0.599999  0.399999
 0.500003  1.0       0.600002  0.400003     0.999984  0.600001  0.400002
 0.599999  0.600002  1.0       0.500001     0.600015  0.999999  0.5
 0.4       0.400003  0.500001  1.0          0.400017  0.500001  0.999999
 0.999986  0.500016  0.599986  0.399986     0.50003   0.599986  0.399986
 0.500016  0.999986  0.600014  0.400015  …  0.999999  0.600014  0.400014
 0.599999  0.600001  0.999999  0.500001     0.600016  1.0       0.5
 0.399999  0.400002  0.5       0.999999     0.400016  0.5       1.0
 0.999985  0.500017  0.599984  0.399985     0.500032  0.599984  0.399984
 0.500018  0.999984  0.600015  0.400017     1.0       0.600016  0.400016
 0.599999  0.600001  0.999999  0.500001  …  0.600016  1.0       0.5
 0.399999  0.400002  0.5       0.999999     0.400016  0.5       1.0

In [58]:
kinship_man(gene_mat)

6×6 Matrix{Float64}:
 1.0       0.726205  0.702411  0.678616  0.654822  0.629842
 0.726205  1.0       0.976205  0.952411  0.928616  0.903637
 0.702411  0.976205  1.0       0.976205  0.952411  0.927431
 0.678616  0.952411  0.976205  1.0       0.976205  0.951226
 0.654822  0.928616  0.952411  0.976205  1.0       0.975021
 0.629842  0.903637  0.927431  0.951226  0.975021  1.0

In [59]:
# testing kinship_lin
function kinship_lin(mat,cross)
r=size(mat,1)/cross; n=size(mat,2)
     K=Symmetric(BLAS.syrk('U','T',1.0,mat))/r
   @views for j=1:n
        K[j,j]=1.0
          end
    return convert(Array{Float64,2},K)
end


kinship_lin (generic function with 1 method)

In [60]:
kinship_lin(gpr,1)

12×12 Matrix{Float64}:
 1.0         1.81101e-6  4.87391e-7  2.67184e-9  …  1.82773e-7   1.55739e-9
 1.81101e-6  1.0         1.17343e-8  7.3113e-7      6.49529e-9   4.26807e-7
 4.87391e-7  1.17343e-8  1.0         6.09239e-7     0.15         4.26468e-7
 2.67184e-9  7.3113e-7   6.09239e-7  1.0            1.82773e-7   0.349999
 0.25        1.46635e-5  3.04623e-7  1.12992e-9     2.57283e-12  9.76623e-14
 1.50606e-6  0.249984    1.10633e-8  3.04648e-7  …  5.82633e-9   3.3946e-10
 1.82773e-7  6.49544e-9  0.15        1.82773e-7     0.15         1.11935e-12
 1.55739e-9  4.26776e-7  4.26468e-7  0.349999       1.12499e-12  0.35
 0.25        1.60827e-5  3.04624e-7  1.13165e-9     2.7425e-12   1.07266e-13
 1.50603e-6  0.249982    1.1063e-8   3.04646e-7     5.82616e-9   3.3946e-10
 1.82773e-7  6.49529e-9  0.15        1.82773e-7  …  1.0          1.12923e-12
 1.55739e-9  4.26807e-7  4.26468e-7  0.349999       1.12923e-12  1.0

In [61]:
kinship_lin(gene_mat,1)

6×6 Matrix{Float64}:
 1.0         0.00917364  0.010309   0.0114443  0.0125796  0.0137711
 0.00917364  1.0         0.0137012  0.0159649  0.0182287  0.0206048
 0.010309    0.0137012   1.0        0.0204856  0.0238778  0.0274384
 0.0114443   0.0159649   0.0204856  1.0        0.0295268  0.0342721
 0.0125796   0.0182287   0.0238778  0.0295268  1.0        0.0411057
 0.0137711   0.0206048   0.0274384  0.0342721  0.0411057  1.0

In [62]:
# testing kinship_ctr
function kinship_ctr(genmat::Array{Float64,2})
   p=size(genmat,1)
    cgene= genmat.-mean(genmat,dims=2)
    # K=(1-ρ)*transpose(cgene)*cgene/n+ρ*Matrix(1.0I,n,n)
     #K=cgene'*cgene/p
     K=Symmetric(BLAS.syrk('U','T',1.0,cgene))/p
    return convert(Array{Float64,2},K)

end

kinship_ctr (generic function with 1 method)

In [63]:
kinship_ctr(gpr)

12×12 Matrix{Float64}:
  0.187498   -0.0624982  -0.0374999  …  -0.0624948  -0.0375001  -0.0875003
 -0.0624982   0.187497   -0.0374998      0.187487   -0.0374997  -0.0874993
 -0.0374999  -0.0374998   0.137499      -0.0374961   0.1375     -0.0624997
 -0.0875002  -0.087499   -0.0624995     -0.0874957  -0.0624998   0.237499
  0.187496   -0.0624887  -0.0375034     -0.0624853  -0.0375036  -0.0875036
 -0.0624952   0.187488   -0.0374965  …   0.187477   -0.0374964  -0.0874964
 -0.0375001  -0.0374997   0.1375        -0.037496    0.1375     -0.0625
 -0.0875003  -0.0874993  -0.0624997     -0.0874961  -0.0625      0.2375
  0.187495   -0.0624876  -0.0375037     -0.0624842  -0.0375039  -0.0875039
 -0.0624948   0.187487   -0.0374961      0.187476   -0.037496   -0.0874961
 -0.0375001  -0.0374997   0.1375     …  -0.037496    0.1375     -0.0625
 -0.0875003  -0.0874993  -0.0624997     -0.0874961  -0.0625      0.2375

In [64]:
kinship_ctr(gene_mat)

6×6 Matrix{Float64}:
  0.180711   -0.030453    -0.0332834   -0.0361139   -0.0389443   -0.0419161
 -0.030453    0.00951165   0.00780964   0.00610763   0.00440563   0.00261845
 -0.0332834   0.00780964   0.00723607   0.00666249   0.00608892   0.00548633
 -0.0361139   0.00610763   0.00666249   0.00721735   0.00777221   0.00835421
 -0.0389443   0.00440563   0.00608892   0.00777221   0.0094555    0.0112221
 -0.0419161   0.00261845   0.00548633   0.00835421   0.0112221    0.014235

In [65]:
# testing kinship_std
function kinship_std(genmat::Array{Float64,2})
    p=size(genmat,1)
    sgene=(genmat.-mean(genmat,dims=2))./std(genmat,dims=2)
   #(1-ρ)*transpose(sgene)*sgene/n+ρ*Matrix(1.0I,n,n)
     K=Symmetric(BLAS.syrk('U','T',1.0,sgene))/p

    return convert(Array{Float64,2},K)
end

kinship_std (generic function with 1 method)

In [66]:
kinship_std(gpr)

12×12 Matrix{Float64}:
  0.916669  -0.305573  -0.183325  …  -0.305556  -0.183326  -0.427772
 -0.305573   0.916731  -0.183358      0.91668   -0.183358  -0.427801
 -0.183325  -0.183358   0.672228     -0.18334    0.67223   -0.305546
 -0.427771  -0.427799  -0.305545     -0.427783  -0.305546   1.16112
  0.916655  -0.305526  -0.183342     -0.30551   -0.183343  -0.427788
 -0.305558   0.916685  -0.183342  …   0.916635  -0.183342  -0.427787
 -0.183326  -0.183358   0.67223      -0.18334    0.672232  -0.305548
 -0.427772  -0.427801  -0.305546     -0.427785  -0.305548   1.16112
  0.916654  -0.305521  -0.183343     -0.305505  -0.183344  -0.427789
 -0.305556   0.91668   -0.18334       0.916629  -0.18334   -0.427785
 -0.183326  -0.183358   0.67223   …  -0.18334    0.672232  -0.305548
 -0.427772  -0.427801  -0.305546     -0.427785  -0.305548   1.16112

In [67]:
kinship_std(gene_mat)

6×6 Matrix{Float64}:
  2.37415     0.592324   0.0604934  -0.471337   -1.00317   -1.55247
  0.592324    0.522763   0.203202   -0.116359   -0.43592   -0.766009
  0.0604934   0.203202   0.0959102  -0.0113814  -0.118673  -0.229551
 -0.471337   -0.116359  -0.0113814   0.0935964   0.198574   0.306907
 -1.00317    -0.43592   -0.118673    0.198574    0.515822   0.843365
 -1.55247    -0.766009  -0.229551    0.306907    0.843365   1.39775

In [68]:
# testing kinship_gs
function kinship_gs(climate::Array{Float64,2},ρ::Float64)
 env=axes(climate,2);
 Kc=zeros(env,env);

    @views for c=env, r=c:length(env)
            Kc[r,c]=exp(-mean(abs.(climate[:,c]-climate[:,r]).^2)/ρ)
            Kc[c,r]=Kc[r,c]
    end

    return Kc

end

kinship_gs (generic function with 1 method)

In [69]:
kinship_gs(gpr,.9)

12×12 Matrix{Float64}:
 1.0       0.573759  0.641182  0.513418  …  0.573776  0.641181  0.513418
 0.573759  1.0       0.641183  0.513421     1.0       0.641183  0.51342
 0.641182  0.641183  1.0       0.573755     0.641203  1.0       0.573754
 0.513418  0.513421  0.573755  1.0          0.513436  0.573755  1.0
 1.0       0.573774  0.641181  0.513418     0.573792  0.64118   0.513417
 0.573774  1.0       0.641201  0.513435  …  1.0       0.641201  0.513433
 0.641181  0.641183  1.0       0.573755     0.641203  1.0       0.573753
 0.513418  0.51342   0.573754  1.0          0.513435  0.573753  1.0
 1.0       0.573776  0.641181  0.513418     0.573794  0.64118   0.513417
 0.573776  1.0       0.641203  0.513436     1.0       0.641203  0.513435
 0.641181  0.641183  1.0       0.573755  …  0.641203  1.0       0.573753
 0.513418  0.51342   0.573754  1.0          0.513435  0.573753  1.0

In [70]:
kinship_gs(gene_mat,.9)

6×6 Matrix{Float64}:
 1.0       0.756516  0.753676  0.748966  0.742421  0.733628
 0.756516  1.0       0.998747  0.994997  0.988779  0.979644
 0.753676  0.998747  1.0       0.998747  0.994997  0.988403
 0.748966  0.994997  0.998747  1.0       0.998747  0.994743
 0.742421  0.988779  0.994997  0.998747  1.0       0.998616
 0.733628  0.979644  0.988403  0.994743  0.998616  1.0

In [71]:
# testing kinship_4way
function kinship_4way(genmat::Array{Float64,2})
    nmar, nind=axes(genmat)
    kmat=zeros(nind,nind);
    dist=zeros(nmar);

    for i=nind
        for j=i:length(nind)
            for k=nmar
                if (genmat[k,i]==genmat[k,j])
                    dist[k]= 0.0
                elseif (genmat[k,i]+genmat[k,j]==5)
                    dist[k]=2.0
                else
                    dist[k]=1.0
                end

            end
        kmat[j,i]=1.0-0.5*mean(dist)
        kmat[i,j]=kmat[j,i]
        end
    end

return kmat

end


kinship_4way (generic function with 1 method)

In [72]:
kinship_4way(gpr)

12×12 Matrix{Float64}:
 1.0    0.5  0.5  0.675  0.5    0.5  0.5    0.5    0.5    0.5  0.5    0.5
 0.5    1.0  0.8  0.5    0.5    0.5  0.5    0.5    0.5    0.5  0.5    0.5
 0.5    0.8  1.0  0.5    0.5    0.5  0.5    0.5    0.5    0.5  0.5    0.5
 0.675  0.5  0.5  1.0    0.5    0.5  0.5    0.5    0.5    0.5  0.5    0.5
 0.5    0.5  0.5  0.5    1.0    0.5  0.5    0.675  0.625  0.5  0.5    0.5
 0.5    0.5  0.5  0.5    0.5    1.0  0.8    0.5    0.5    0.6  0.5    0.5
 0.5    0.5  0.5  0.5    0.5    0.8  1.0    0.5    0.5    0.5  0.575  0.5
 0.5    0.5  0.5  0.5    0.675  0.5  0.5    1.0    0.5    0.5  0.5    0.675
 0.5    0.5  0.5  0.5    0.625  0.5  0.5    0.5    1.0    0.5  0.5    0.675
 0.5    0.5  0.5  0.5    0.5    0.6  0.5    0.5    0.5    1.0  0.8    0.5
 0.5    0.5  0.5  0.5    0.5    0.5  0.575  0.5    0.5    0.8  1.0    0.5
 0.5    0.5  0.5  0.5    0.5    0.5  0.5    0.675  0.675  0.5  0.5    1.0

In [73]:
kinship_4way(gene_mat)

6×6 Matrix{Float64}:
 1.0  0.5    0.5    0.5    0.5    0.5
 0.5  1.0    0.625  0.625  0.625  0.625
 0.5  0.625  1.0    0.625  0.625  0.625
 0.5  0.625  0.625  1.0    0.625  0.625
 0.5  0.625  0.625  0.625  1.0    0.625
 0.5  0.625  0.625  0.625  0.625  1.0

***All proporties of kinship are satisfied.***

In [75]:
A=ones(4,8)*7

4×8 Matrix{Float64}:
 7.0  7.0  7.0  7.0  7.0  7.0  7.0  7.0
 7.0  7.0  7.0  7.0  7.0  7.0  7.0  7.0
 7.0  7.0  7.0  7.0  7.0  7.0  7.0  7.0
 7.0  7.0  7.0  7.0  7.0  7.0  7.0  7.0

In [84]:
kinship_ctr(A)

8×8 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0